from app.main.exceptions.mlmb_exception import MlmbException

class ModelException(MlmbException):

    def __init__(self):
        pass